language: node_js
node_js:
  - "stable"
  - "11"
  - "10"
  - "9"
  - "8"

script:
  - npm run test:ci
after_script:
  - 'if [[ x$TRAVIS_NODE_VERSION == xstable ]]; then npm i -g coveralls; ./node_modules/.bin/nyc report --reporter=text-lcov | coveralls; fi'

before_deploy:
  - cd example && npm install && cd ..
  - mkdir _deploy
  - cp example/bundle.js example/index.html _deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _deploy
  on:
    branch: master
    node: stable
